version: 0.0
os: linux
files:
  - source: /
    destination: /opt/gagga-front
    overwrite: yes

permissions:
  - object: /opt/gagga-front
    pattern: '**'
    owner: ec2-user
    group: ec2-user
    mode: 755

  - object: /opt/gagga-front/.env
    owner: ec2-user
    group: ec2-user
    mode: 600

hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root

  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: root
