name: Deploy React App

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Load environment variables from Parameter Store
        run: |
          echo "Loading all environment variables"

          # jq 설치 (JSON 파싱용)
          sudo apt-get update && sudo apt-get install -y jq

          echo "📱 Loading environment variables..."
          aws ssm get-parameters-by-path \
            --path "/gagga/front/prod" \
            --recursive \
            --with-decryption \
            --output json > params.json

          jq -r '.Parameters[] | "\(.Name | split("/") | last | ascii_upcase)=\(.Value)"' params.json > .env
                    
          rm -f params.json

      - name: Build React app
        run: npm run build

      - name: Create deployment package
        run: |
          mkdir -p deploy-package 
          cp -r build/* deploy-package/
          cp appspec.yml deploy-package/
          cp .env deploy-package/
          cp -r scripts deploy-package/
          cd deploy-package
          zip -r ../deployment-package.zip .

      - name: Upload to S3
        run: |
          aws s3 cp deployment-package.zip s3://${{ secrets.AWS_S3_BUCKET_NAME }}/react-app-${{ github.sha }}.zip

      - name: Deploy with CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name ${{ secrets.AWS_CODEDEPLOY_APPLICATION_NAME }} \
            --deployment-group-name ${{ secrets.AWS_CODEDEPLOY_DEPLOYMENT_GROUP }} \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --s3-location bucket=${{ secrets.AWS_S3_BUCKET_NAME }},key=react-app-${{ github.sha }}.zip,bundleType=zip \
            --description "Deployment from GitHub Actions - ${{ github.sha }}"

      - name: Check deployment status
        run: |
          DEPLOYMENT_ID=$(aws deploy list-deployments \
            --application-name ${{ secrets.AWS_CODEDEPLOY_APPLICATION_NAME }} \
            --deployment-group-name ${{ secrets.AWS_CODEDEPLOY_DEPLOYMENT_GROUP }} \
            --query 'deployments[0]' \
            --output text)

          echo "Deployment ID: $DEPLOYMENT_ID"
          aws deploy get-deployment --deployment-id $DEPLOYMENT_ID
